// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejbaodaxyjvelffcrfyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqYmFvZGF4eWp2ZWxmZmNyZnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzU4MTIsImV4cCI6MjA2NTQxMTgxMn0.Z1H6shQDzsEFjtFXipFscy2qgcOe_4t7KOUoorL_0RQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);